USE BTA
GO
INSERT INTO Drzava VALUES 
(N'Andorra',N' AD',N'',N'',N'',N'',N''),
(N'United Arab Emirates',N' AE',N'',N'',N'',N'',N''),
(N'Afghanistan',N' AF',N'',N'',N'',N'',N''),
(N'Antigua and Barbuda',N' AG',N'',N'',N'',N'',N''),
(N'Anguilla',N' AI',N'',N'',N'',N'',N''),
(N'Albania',N' AL',N'',N'',N'',N'',N''),
(N'Armenia',N' AM',N'',N'',N'',N'',N''),
(N'Netherlands Antilles',N' AN',N'',N'',N'',N'',N''),
(N'Angola',N' AO',N'',N'',N'',N'',N''),
(N'Argentina',N' AR',N'',N'',N'',N'',N''),
(N'Austria',N' AT',N'',N'',N'',N'',N''),
(N'Australia',N' AU',N'',N'',N'',N'',N''),
(N'Aruba',N' AW',N'',N'',N'',N'',N''),
(N'Azerbaijan',N' AZ',N'',N'',N'',N'',N''),
(N'Bosnia and Herzegovina',N' BA',N'',N'',N'',N'',N''),
(N'Barbados',N' BB',N'',N'',N'',N'',N''),
(N'Bangladesh',N' BD',N'',N'',N'',N'',N''),
(N'Belgium',N' BE',N'',N'',N'',N'',N''),
(N'Burkina Faso',N' BF',N'',N'',N'',N'',N''),
(N'Bulgaria',N' BG',N'',N'',N'',N'',N''),
(N'Bahrain',N' BH',N'',N'',N'',N'',N''),
(N'Burundi',N' BI',N'',N'',N'',N'',N''),
(N'Benin',N' BJ',N'',N'',N'',N'',N''),
(N'Bermuda',N' BM',N'',N'',N'',N'',N''),
(N'Brunei Darussalam',N' BN',N'',N'',N'',N'',N''),
(N'Bolivia',N' BO',N'',N'',N'',N'',N''),
(N'Brazil',N' BR',N'',N'',N'',N'',N''),
(N'Bahamas',N' BS',N'',N'',N'',N'',N''),
(N'Bhutan',N' BT',N'',N'',N'',N'',N''),
(N'Botswana',N' BW',N'',N'',N'',N'',N''),
(N'Belarus',N' BY',N'',N'',N'',N'',N''),
(N'Belize',N' BZ',N'',N'',N'',N'',N''),
(N'Canada',N' CA',N'Transport Canada continues making progress in implementing initiatives under Transportation 2030. In May 2018, the Transportation Modernization Act received Royal Assent. This is an important legislative step toward improving the air passenger experience as well as the safety and efficiency of the rail system.In addition, other initiatives continue to be implemented including the Oceans Protection Plan, the Pan-Canadian Framework on Clean Growth and Climate Change, the Trade and Transportation Corridors Initiative, which includes the Canadian Centre on Transportation Data.To further improve the safety of the Canadian transportation system in 2017, the Minister of Transport launched the Statutory Review of the Railway Safety Act, introduced the Transportation Modernization Act and is strengthening the Motor Vehicle Safety Act. Safety in the transportation of dangerous goods was also strengthened across Canada through increased inspections, regulations updates, and outreach and awareness to stakeholders. Canada also continued its work to facilitate the flow of legitimate passengers and freight while maintaining a high level of security through inspections, information sharing and stakeholder engagements.Through the summer and fall of 2017, the Government of Canada also successfully implemented a vessel speed restriction zone for large vessels passing through a large portion of the Gulf of St. Lawrence. This action substantially reduced the risk of fatal vessel strikes for the endangered North Atlantic right whale population that resided in the area during this period.In 2017, the Government of Canada continued its efforts to ensure transportation is increasingly environmentally responsible through different measures including: work on the development of a Canada-wide strategy for zero-emission vehicles in collaboration with provincial and territorial governments, the implementation of carbon dioxide standards for new airplanes, the publishing of draft greenhouse gases (GHG) regulations for heavy duty road vehicles, the development of the Locomotive Emission Regulations, and the entry into force of the Ballast Water Control and Management Regulations.In 2017, the Government of Canada also announced a number of measures through the Oceans Protection Plan’s initiatives to strengthen environmental protection, prevent marine incidents and improve emergency response capacity. ',N'Canadian cuisine varies widely depending on the regions of the nation. The three earliest cuisines of Canada have First Nations, English, Scottish and French roots, with the traditional cuisine of English Canada closely related to British cuisine, while the traditional cuisine of French Canada has evolved from French cuisine and the winter provisions of fur traders. With subsequent waves of immigration in the 19th and 20th century from Central, Southern, and Eastern Europe, South Asia, East Asia, and the Caribbean, the regional cuisines were subsequently augmented.',N'Canada is a very safe country, and is often viewed as a safe haven compared to the US where crime and violence is still an issue. Canada is ranked 8th out of 162 on the safest and most dangerous countries ranking. Emergency numbers 112 redirects to 911 on mobile phones. ',N'Canada is a country with a rich cultural heritage. In Canada, festivals and events are held annually to celebrate the multicultural landscape of this great nation. Each festival represents a single cultural facet belonging to the diverse population of Canada. These festivals are easily identified by season. ',N'Halifax , St John''s, Winnipeg,  Edmonton,  Regina,  Saskatoon , Kelowna,  Victoria.  '),
(N'Cocos (Keeling) Islands',N' CC',N'',N'',N'',N'',N''),
(N'Democratic Republic of the Congo',N' CD',N'',N'',N'',N'',N''),
(N'Central African Republic',N' CF',N'',N'',N'',N'',N''),
(N'Congo',N' CG',N'',N'',N'',N'',N''),
(N'Switzerland',N' CH',N'',N'',N'',N'',N''),
(N'Cote DIvoire (Ivory Coast)',N' CI',N'',N'',N'',N'',N''),
(N'Cook Islands',N' CK',N'',N'',N'',N'',N''),
(N'Chile',N' CL',N'',N'',N'',N'',N''),
(N'Cameroon',N' CM',N'',N'',N'',N'',N''),
(N'China',N' CN',N'',N'',N'',N'',N''),
(N'Colombia',N' CO',N'',N'',N'',N'',N''),
(N'Costa Rica',N' CR',N'',N'',N'',N'',N''),
(N'Cuba',N' CU',N'',N'',N'',N'',N''),
(N'Cape Verde',N' CV',N'',N'',N'',N'',N''),
(N'Christmas Island',N' CX',N'',N'',N'',N'',N''),
(N'Cyprus',N' CY',N'',N'',N'',N'',N''),
(N'Czech Republic',N' CZ',N'',N'',N'',N'',N''),
(N'Germany',N' DE',N'Public Transport in Germany and Europe is usually excellent. It is very practical to live in any large German city or metropolitan area without owning a car. Even medium-sized cities have good public transportation networks that use buses, trams, and urban/suburban rail lines to move people around. Because most public transportation systems in Germany are regional, a ticket for the S-Bahn is also valid for a streetcar or bus. For instance, the S-Bahn in Berlin is a subsidiary of Deutsche Bahn, the national railway, but it is also part of the Transport Association Berlin-Brandenburg (VBB). That means a ticket bought at an S-Bahn station is also valid for buses, the U-Bahn, or trams. If you buy a ticket from a bus driver (normal practice in Berlin), it is also valid for the S-Bahn, as long as you use it within two hours of your purchase. Tickets are also available at multilingual ticket machines on platforms or at sales points in major stations. Berlin, Frankfurt, and some other cities also offer Kurzstrecke (“short route”) tickets that are good for a maximum of three stops. If you buy a short-route ticket and then travel past the limit, it’s the same as having no ticket. Most people buy a ticket from a ticket machine (Fahrkarten-/Ticketautomat), but in Berlin and some other cities you can also purchase a normal, season, or special ticket from a ticket office during normal business hours. “Customer Centre” ticket offices are located in larger stations and at BVG’s headquarters on Holzmarktstraße. Tickets are also available online and via a smartphone app (see below). You usually need to know which zone(s) you’ll be traveling in. See more about zones and special tickets below.',N'Mention traditional German food and most people tend to think of sausage, sauerkraut and beer - but German food is much more than these tree things. German food are pork based and include hearty stews and lots of potato dishes, German food includes a great varitety of fresh local produce, and seafood depending on which area of fresh local produce, and seafood depending on which area of the country you are in. Germany has a long culinary history reflecting its rural roots and geography.  ',N'While a very safe country, some parts of the Germany''s cities are best to be avoided, and pickpockets can be a problem near some touristic landmarks in London. The Germany is the 14rd safest country in the world, based on the safest and most dangerous countries ranking. Emergency calls can be made from any phone free of charge: call 110 for police and 112 for fire and ambulance. ',N'German culture has spanned the entire German-speaking world. From its roots, culture in Germany has been shaped by major intellectual and popular currents in Europe, both religious and secular. There are a number of public holidays. The country is particularly known for its traditional Oktoberfest celebrations in Munich, its carnival culture and globally influential Christmas customs known as Weihnachten. The UNESCO inscribed 38 properties in Germany on the World Heritage List.',N'Frankfurt Airport, Dusseldorf Airport, Munich Airport, Berlin Tegel Airport, Stuttgart Airport'),
(N'Djibouti',N' DJ',N'',N'',N'',N'',N''),
(N'Denmark',N' DK',N'',N'',N'',N'',N''),
(N'Dominica',N' DM',N'',N'',N'',N'',N''),
(N'Dominican Republic',N' DO',N'',N'',N'',N'',N''),
(N'Algeria',N' DZ',N'',N'',N'',N'',N''),
(N'Ecuador',N' EC',N'',N'',N'',N'',N''),
(N'Estonia',N' EE',N'',N'',N'',N'',N''),
(N'Egypt',N' EG',N'',N'',N'',N'',N''),
(N'Western Sahara',N' EH',N'',N'',N'',N'',N''),
(N'Eritrea',N' ER',N'',N'',N'',N'',N''),
(N'Spain',N' ES',N'Public transportation in Spain ranges from modern metros to well-connected speed rails between major Spanish cities, and it’s among the best in Europe. As a bonus, using Spain’s public transport system instead of driving yourself can help reduce the cost of getting around the country.There are underground railway systems (metros) in major Spanish cities such as Madrid, Barcelona, Bilbao, Malaga, Seville and Valencia, and tickets and passes allow travel on all modes of public transport including metro, bus and suburban train services.Metros offer the quickest way to get around these cities, although they can become very crowded during rush hours. No smoking is permitted on metro trains or in stations, which are clean and fairly safe.Crime is generally rare on Spanish metros, although you should watch out for pickpockets, especially on the Madrid system.Madrid has the largest and oldest metro system in Spain with 13 lines (plus one branch) and 300 stations covering most of the city, operating from 6am until 1.30am and used by some three million people daily.The fare is €2.00 per journey for most lines (€1.50 for select lines only) or €18.30 for a 10-journey ticket across all of the stations in the Metro Network and Metro Ligero: ML1, ML2 and ML3, which may include bus travel (metrobús).30-day or annual season tickets are available for young people aged under 23 (abono joven), commuters (abono normal) and for pensioners over 65 (abono tercera edad). Season tickets offer exceptionally good savings for unlimited travel on public transport including the underground, city buses and local trains (cercanías). Pensioners who pay only €12.30 a month for unlimited travel get a particularly good deal.',N'Spanish cuisine is heavily influenced by historical processes that shaped local culture and society in some of Europe''s Iberian Peninsula territories. Geography and climate had great influence on cooking methods and available ingredients. These cooking methods and ingredients are still present in the gastronomy of the various regions that make up Spain. Spanish cuisine derives from a complex history where invasions and conquests of Spain have modified traditions which made new ingredients available. Thus, the current and old cuisine of Spain incorporates old and new traditions. ',N'Spain is the world''s third most-visited country, especially around its main cities. SafeAround has compiled information from numerous sources make sure you have a safe trip in Spain and be aware of all potential dangers. Spain is very safe: it is ranked 17th out of 162 on the safest and most dangerous countries ranking. Emergency calls can be made from any phone free of charge: call 112 for police, fire and ambulance.',N'The culture of Spain is based on a variety of historical influences, primarily based on pre-Roman Celtic and Iberian culture.[citation needed] Other ancient peoples such as Romans, Phoenicians, Carthaginians, and Greeks also had some influence. In the areas of language and also religion, the Ancient Romans left a lasting legacy in the Spanish culture because Rome created Hispania as a political, legal and administrative unit. The subsequent course of Spanish history added other elements to the country''s culture and traditions.',N'Gran Canaria Airport, San Pablo Airport, Ibiza Airport, Madrid-Barajas Airport, Palma de Mallorca Airport, Bilbao Airport'),
(N'Ethiopia',N' ET',N'',N'',N'',N'',N''),
(N'Finland',N' FI',N'',N'',N'',N'',N''),
(N'Fiji',N' FJ',N'',N'',N'',N'',N''),
(N'Falkland Islands (Malvinas)',N' FK',N'',N'',N'',N'',N''),
(N'Federated States of Micronesia',N' FM',N'',N'',N'',N'',N''),
(N'Faroe Islands',N' FO',N'',N'',N'',N'',N''),
(N'France',N' FR',N'The first important human improvements were the Roman roads linking major settlements and providing quick passage for marching armies. All through the Middle Ages improvements were few and second rate. Transport became slow and awkward to use. The early modern period saw great improvements. There was a very quick production of canals connecting rivers. It also saw great changes in oceanic shipping. Rather than expensive galleys, wind powered ships that were much faster and had more room for cargo became popular for coastal trade. Transatlantic shipping with the New World turned cities such as Nantes, Bordeaux, Cherbourg-Octeville and Le Havre into major ports. Six cities in France currently have a rapid transit service (frequently known as a ''metro''). Full metro systems are in operation in Paris (16 lines), Lyon (4 lines) and Marseille (2 lines). Light metro (VAL-type) systems are in use in Lille (2 lines), Toulouse (2 lines) and Rennes (1 line).',N'There are many places to try French food in France, from three-star Michelin restaurants to French "brasseries" or "bistros. These usually offer a relatively consistent and virtually standardised menu of relatively inexpensive cuisine. To obtain a greater variety of dishes, a larger outlay of money is often necessary. One should try to eat where the locals do for the best chance of a memorable meal. There are also specific local restaurants, like "bouchons lyonnais", "crêperies" , etc. ',N'Even if France is a low-crime area, the murder rate is about the double of the surrounding countries and large cities are plagued with the usual woes. Violent crime against tourists or strangers is rare, but there is pickpocketing and purse-snatching.  Hospitals will have an emergency room signposted Urgences.The following numbers are toll-free: 15 - Medical emergencies, 17 - Law enforcement emergencies (for e.g. reporting a crime), 18 - Firefighters, 112 - European standard emergency numbers.Operators at these numbers can transfer requests to other services if needed. ',N'Most people associate French culture with Paris, which is a center of fashion, cuisine, art and architecture, but life outside of the City of Lights is very different and varies by region. Historically, French culture was influenced by Celtic and Gallo-Roman cultures as well as the Franks, a Germanic tribe. France was initially defined as the western area of Germany known as Rhineland but it later came to refer to a territory that was known as Gaul during the Iron Age and Roman era.',N'Roissy - Charles de Gaulle , Orly,  Beauvais airport'),
(N'Gabon',N' GA',N'',N'',N'',N'',N''),
(N'Great Britain (UK)',N' GB',N'There are a number of railway and train operators in the UK, with Network Rail managing most of the national network.Intercity bus services are plentiful and often cheaper than trains, while local bus networks can be found in most municipalities.Taxis and ordered minicabs are also key players in local public transportation. However, a ride in an iconic black cab in London will be significantly more expensive than a bus journey.Since its introduction in London in 2012, Uber has grown to be a competitive alternative to taxis in many big British cities.Ferry connections provide not only easy access to neighboring countries, but also along the Scottish Highlands and to Northern Ireland and the smaller British islands.Public transportation in the UK includes a comprehensive railway system that allows you to reach almost every smaller or bigger town by train — the system is in fact the oldest in the world. There are different companies which maintain the national and regional networks, with Network Rail managing the majority of the national network in Great Britain, and NI Railways managing the railroad traffic in Northern Ireland.The price of your train ticket is typically determined by the distance and time of your journey. However, which network you are traveling on as well as how far in advance you book your ticket can make a significant difference as well. You can look up times, connections, and prices as well as book your tickets on National Rail Enquiries.',N'British cuisine is the heritage of cooking traditions and practices associated with the United Kingdom. Although Britain has a rich indigenous culinary tradition its colonial history has profoundly enriched its native cooking traditions. British cuisine absorbed the cultural influences of its post-colonial territories – in particular those of South Asia. Well-known traditional British dishes include full breakfast, fish and chips, the Christmas dinner,the Sunday roast, steak and kidney pie, shepherd''s pie. ',N'While a very safe country, some parts of the UK''s cities are best to be avoided, and pickpockets can be a problem near some touristic landmarks in London. The UK is the 33rd safest country in the world, based on the safest and most dangerous countries ranking. Emergency calls can be made from any phone free of charge: call 112 or 999 for police, fire and ambulance.',N'The United Kingdom''s culture is influenced by its history as a developed state, a liberal democracy and a great power; its predominantly Christian religious life; and its composition of four countries—England, Scotland, Wales and Northern Ireland—each of which has distinct customs, cultures and symbolism. British literature, music, cinema, art, theatre, media, television and education are important aspects of British culture. The UK has been described as a "cultural superpower" and London has been described as a world cultural capital.',N'Heathrow Airport, London City Airport, Luton Airport, Stansend Airport, Gatwick Airport'),
(N'Grenada',N' GD',N'',N'',N'',N'',N''),
(N'Georgia',N' GE',N'',N'',N'',N'',N''),
(N'French Guiana',N' GF',N'',N'',N'',N'',N''),
(N'NULL',N' GG',N'',N'',N'',N'',N''),
(N'Ghana',N' GH',N'',N'',N'',N'',N''),
(N'Gibraltar',N' GI',N'',N'',N'',N'',N''),
(N'Greenland',N' GL',N'',N'',N'',N'',N''),
(N'Gambia',N' GM',N'',N'',N'',N'',N''),
(N'Guinea',N' GN',N'',N'',N'',N'',N''),
(N'Guadeloupe',N' GP',N'',N'',N'',N'',N''),
(N'Equatorial Guinea',N' GQ',N'',N'',N'',N'',N''),
(N'Greece',N' GR',N'',N'',N'',N'',N''),
(N'S. Georgia and S. Sandwich Islands',N' GS',N'',N'',N'',N'',N''),
(N'Guatemala',N' GT',N'',N'',N'',N'',N''),
(N'Guinea-Bissau',N' GW',N'',N'',N'',N'',N''),
(N'Guyana',N' GY',N'',N'',N'',N'',N''),
(N'Hong Kong',N' HK',N'',N'',N'',N'',N''),
(N'Honduras',N' HN',N'',N'',N'',N'',N''),
(N'Croatia (Hrvatska)',N' HR',N'',N'',N'',N'',N''),
(N'Haiti',N' HT',N'',N'',N'',N'',N''),
(N'Hungary',N' HU',N'',N'',N'',N'',N''),
(N'Indonesia',N' ID',N'',N'',N'',N'',N''),
(N'Ireland',N' IE',N'',N'',N'',N'',N''),
(N'Israel',N' IL',N'',N'',N'',N'',N''),
(N'India',N' IN',N'',N'',N'',N'',N''),
(N'Iraq',N' IQ',N'',N'',N'',N'',N''),
(N'Iran',N' IR',N'',N'',N'',N'',N''),
(N'Iceland',N' IS',N'',N'',N'',N'',N''),
(N'Italy',N' IT',N'',N'',N'',N'',N''),
(N'Jamaica',N' JM',N'',N'',N'',N'',N''),
(N'Jordan',N' JO',N'',N'',N'',N'',N''),
(N'Japan',N' JP',N'Japan has an efficient public transportation network, especially within metropolitan areas and between the large cities. Japanese public transportation is characterized by its punctuality, its superb service, and the large crowds of people using it.Transportation in Japan is modern and highly developed. Japan''s transport sector stands out for its energy efficiency: it uses less energy per person compared to other countries, thanks to a high share of rail transport and low overall travel distances.Transport in Japan is also very expensive in international comparison, reflecting high tolls and taxes, particularly on automobile transport.Japan''s spending on roads has been large.The 1.2 million kilometres of paved road are the main means of transport.Japan has left-hand traffic. A single network of high-speed, divided, limited-access toll roads connects major cities, which are operated by toll-collecting enterprises. ',N'There are many places to try French food in France, from three-star Michelin restaurants to French "brasseries" or "bistros. These usually offer a relatively consistent and virtually standardised menu of relatively inexpensive cuisine. To obtain a greater variety of dishes, a larger outlay of money is often necessary. One should try to eat where the locals do for the best chance of a memorable meal. There are also specific local restaurants, like "bouchons lyonnais", "crêperies" , etc. ',N'Even if France is a low-crime area, the murder rate is about the double of the surrounding countries and large cities are plagued with the usual woes. Violent crime against tourists or strangers is rare, but there is pickpocketing and purse-snatching. Hospitals will have an emergency room signposted Urgences.The following numbers are toll-free: 15 - Medical emergencies, 17 - Law enforcement emergencies (for e.g. reporting a crime), 18 - Firefighters, 112 - European standard emergency numbers.Operators at these numbers can transfer requests to other services if needed. ',N'Most people associate French culture with Paris, which is a center of fashion, cuisine, art and architecture, but life outside of the City of Lights is very different and varies by region. Historically, French culture was influenced by Celtic and Gallo-Roman cultures as well as the Franks, a Germanic tribe. France was initially defined as the western area of Germany known as Rhineland but it later came to refer to a territory that was known as Gaul during the Iron Age and Roman era.',N'Roissy - Charles de Gaulle, Orly, Beauvais airport'),
(N'Kenya',N' KE',N'',N'',N'',N'',N''),
(N'Kyrgyzstan',N' KG',N'',N'',N'',N'',N''),
(N'Cambodia',N' KH',N'',N'',N'',N'',N''),
(N'Kiribati',N' KI',N'',N'',N'',N'',N''),
(N'Comoros',N' KM',N'',N'',N'',N'',N''),
(N'Saint Kitts and Nevis',N' KN',N'',N'',N'',N'',N''),
(N'Korea (North)',N' KP',N'',N'',N'',N'',N''),
(N'Korea (South)',N' KR',N'',N'',N'',N'',N''),
(N'Kuwait',N' KW',N'',N'',N'',N'',N''),
(N'Cayman Islands',N' KY',N'',N'',N'',N'',N''),
(N'Kazakhstan',N' KZ',N'',N'',N'',N'',N''),
(N'Laos',N' LA',N'',N'',N'',N'',N''),
(N'Lebanon',N' LB',N'',N'',N'',N'',N''),
(N'Saint Lucia',N' LC',N'',N'',N'',N'',N''),
(N'Liechtenstein',N' LI',N'',N'',N'',N'',N''),
(N'Sri Lanka',N' LK',N'',N'',N'',N'',N''),
(N'Liberia',N' LR',N'',N'',N'',N'',N''),
(N'Lesotho',N' LS',N'',N'',N'',N'',N''),
(N'Lithuania',N' LT',N'',N'',N'',N'',N''),
(N'Luxembourg',N' LU',N'',N'',N'',N'',N''),
(N'Latvia',N' LV',N'',N'',N'',N'',N''),
(N'Libya',N' LY',N'',N'',N'',N'',N''),
(N'Morocco',N' MA',N'',N'',N'',N'',N''),
(N'Monaco',N' MC',N'',N'',N'',N'',N''),
(N'Moldova',N' MD',N'',N'',N'',N'',N''),
(N'Madagascar',N' MG',N'',N'',N'',N'',N''),
(N'Marshall Islands',N' MH',N'',N'',N'',N'',N''),
(N'Macedonia',N' MK',N'',N'',N'',N'',N''),
(N'Mali',N' ML',N'',N'',N'',N'',N''),
(N'Myanmar',N' MM',N'',N'',N'',N'',N''),
(N'Mongolia',N' MN',N'',N'',N'',N'',N''),
(N'Macao',N' MO',N'',N'',N'',N'',N''),
(N'Northern Mariana Islands',N' MP',N'',N'',N'',N'',N''),
(N'Martinique',N' MQ',N'',N'',N'',N'',N''),
(N'Mauritania',N' MR',N'',N'',N'',N'',N''),
(N'Montserrat',N' MS',N'',N'',N'',N'',N''),
(N'Malta',N' MT',N'',N'',N'',N'',N''),
(N'Mauritius',N' MU',N'',N'',N'',N'',N''),
(N'Maldives',N' MV',N'',N'',N'',N'',N''),
(N'Malawi',N' MW',N'',N'',N'',N'',N''),
(N'Mexico',N' MX',N'Air travel is the fastest and most convenient way to get from one destination to another, particularly if you''ll be covering long distances. Buses are the main form of long-distance public transportation in Mexico. There is an extensive network of buses, which range from modern luxury coaches to retired school buses. If you''re planning a long journey, travel in the highest class your budget will allow: the extra comfort is worth the cost. During high season you should book your bus trip in advance, during the low season, you can buy tickets on the spot.Unfortunately, passenger train service has been discontinued in most of Mexico. You can still ride Mexico''s most famous train, affectionately known as "El Chepe," on the Copper Canyon Railway.Mexico is a popular cruise destination, with many beautiful and fascinating ports of call, both along the Mexican Riviera (the Pacific coast) and the Riviera Maya (the Mexican Caribbean). A colectivo can be a car, van or pick-up truck that operates as a shared taxi, covering a specific route. They will generally stop anywhere along their route to pick up or drop off passengers. Colectivos charge per person, and the drivers will try to fit in as many people as possible, which can make for an uncomfortable ride. Mototaxis known as rickshaws or tuk-tuks in other parts of the world, but in Latin America, these three-wheeled contraptions with a bench seat in the back are called mototaxis. They operate in small towns and on the outskirts of big cities.Although it''s becoming less and less common, in Mexico''s rural areas you may still come across someone riding a burro. ',N'Mexican cuisine can be described better as a collection of various regional cuisines rather than a standard list of dishes for the whole country. Because of climate, geography and ethnic differences, we can classify Mexican cuisine broadly in 4 great categories according to the region: Northern, Central, Southeastern, Coast.',N'Mexico''s emergency number is 911, call this number for any emergency service: such as police, medical, fire, etc. Some cities, such as Guadalajara and Mexico City, are safer than most places in Mexico. However, caution is still recommended. Emergency calls can be made from any phone free of charge: call 911 for police, fire and ambulance.',N'The culture of Mexico reflects the country''s complex history and is the result of the gradual blending of native culture (particularly Mesoamerican) with Spanish culture and other immigrant cultures. First inhabited more than 10,000 years ago, the cultures that developed in Mexico became one of the cradles of civilization. During the 300-year rule by the Spanish, Mexico acrossroad for the people and cultures of Europe, Africa, and Asia. The government of independent Mexico actively promoted shared cultural traits in order to create a national identity.',N'Aeropuerto Internacional Benito Juárez, Cancún International Airport,General Juan N. Álvarez,International Airport,Lic. Jesús Terán Peredo International Airport,Agualeguas National Airport,Álamos National Airport,General Mariano Matamoros Airport,Isla Guadalupe Airport'),
(N'Malaysia',N' MY',N'',N'',N'',N'',N''),
(N'Mozambique',N' MZ',N'',N'',N'',N'',N''),
(N'Namibia',N' NA',N'',N'',N'',N'',N''),
(N'New Caledonia',N' NC',N'',N'',N'',N'',N''),
(N'Niger',N' NE',N'',N'',N'',N'',N''),
(N'Norfolk Island',N' NF',N'',N'',N'',N'',N''),
(N'Nigeria',N' NG',N'',N'',N'',N'',N''),
(N'Nicaragua',N' NI',N'',N'',N'',N'',N''),
(N'Netherlands',N' NL',N'',N'',N'',N'',N''),
(N'Norway',N' NO',N'',N'',N'',N'',N''),
(N'Nepal',N' NP',N'',N'',N'',N'',N''),
(N'Nauru',N' NR',N'',N'',N'',N'',N''),
(N'Niue',N' NU',N'',N'',N'',N'',N''),
(N'New Zealand (Aotearoa)',N' NZ',N'',N'',N'',N'',N''),
(N'Oman',N' OM',N'',N'',N'',N'',N''),
(N'Panama',N' PA',N'',N'',N'',N'',N''),
(N'Peru',N' PE',N'',N'',N'',N'',N''),
(N'French Polynesia',N' PF',N'',N'',N'',N'',N''),
(N'Papua New Guinea',N' PG',N'',N'',N'',N'',N''),
(N'Philippines',N' PH',N'',N'',N'',N'',N''),
(N'Pakistan',N' PK',N'',N'',N'',N'',N''),
(N'Poland',N' PL',N'',N'',N'',N'',N''),
(N'Saint Pierre and Miquelon',N' PM',N'',N'',N'',N'',N''),
(N'Pitcairn',N' PN',N'',N'',N'',N'',N''),
(N'Palestinian Territory',N' PS',N'',N'',N'',N'',N''),
(N'Portugal',N' PT',N'',N'',N'',N'',N''),
(N'Palau',N' PW',N'',N'',N'',N'',N''),
(N'Paraguay',N' PY',N'',N'',N'',N'',N''),
(N'Qatar',N' QA',N'',N'',N'',N'',N''),
(N'Reunion',N' RE',N'',N'',N'',N'',N''),
(N'Romania',N' RO',N'',N'',N'',N'',N''),
(N'Russian Federation',N' RU',N'Road safety in Russia is poor, with a road accident rate higher than in Europe or the United States.In 2011, Russia was 4th by number of absolute recorded road deaths.Increasingly harsher penalties for traffic violations were imposed after 2008, but the level of corruption among traffic law enforcement authorities limits their effectiveness in reducing the number of accidents.As of 2002, there were 2,743 airports in Russia.Since 2013, the Russian government subsidizes about 140 domestic air routes covering 12 airports.The subsidies are managed by Rosaviatsia and cover the Crimea, Kaliningrad and Far East regions of Russia.',N'Russian cuisine derives its rich and varied character from the vast and multicultural expanse of Russia. Its foundations were laid by the peasant food of the rural population in an often harsh climate, with a combination of plentiful fish, poultry, game, mushrooms, berries, and honey. Crops of rye, wheat, buckwheat, barley, and millet provided the ingredients for a plethora of breads, pancakes, cereals, kvass, beer, and vodka.',N'For the average tourist, Moscow, Saint Petersburg and the rest of Russia are actually just as safe as most major European cities, if not more so. Emergency services (landlines): 01 - fire fighting and lifeguard, 02 - police, 03 - emergency medical aid, 04 - gas emergencies Emergency services (mobile phone): First dial 112 and after hearing the voice dial the extra number: 1 - fire fighting and lifeguard, 2 - police, 3 - emergency medical aid, 4 - gas emergencies ',N'Russia has several of the world''s greatest museums, The Hermitage Museum in Saint Petersburg. Equally impressive is the edifice housing the collection on display, the magnificent Winter Palace of the Romanov Dynasty.  Moscow''s art museums, include the Tretyakov Gallery (the premiere collection of Russian art) and the Pushkin Museum of Western Art.The best of the big city museums include the Bulgakov Museum in Moscow and the Anna Akhmatova, Pushkin, and Dostoevsky museums in Saint Petersburg.',N'Airport Sheremetyevo SVO Domodedovo DME Vnukovo VKO There are airports in all large cities in Russia.'),
(N'Rwanda',N' RW',N'',N'',N'',N'',N''),
(N'Saudi Arabia',N' SA',N'',N'',N'',N'',N''),
(N'Solomon Islands',N' SB',N'',N'',N'',N'',N''),
(N'Seychelles',N' SC',N'',N'',N'',N'',N''),
(N'Sudan',N' SD',N'',N'',N'',N'',N''),
(N'Sweden',N' SE',N'',N'',N'',N'',N''),
(N'Singapore',N' SG',N'',N'',N'',N'',N''),
(N'Saint Helena',N' SH',N'',N'',N'',N'',N''),
(N'Slovenia',N' SI',N'',N'',N'',N'',N''),
(N'Svalbard and Jan Mayen',N' SJ',N'',N'',N'',N'',N''),
(N'Slovakia',N' SK',N'',N'',N'',N'',N''),
(N'Sierra Leone',N' SL',N'',N'',N'',N'',N''),
(N'San Marino',N' SM',N'',N'',N'',N'',N''),
(N'Senegal',N' SN',N'',N'',N'',N'',N''),
(N'Somalia',N' SO',N'',N'',N'',N'',N''),
(N'Suriname',N' SR',N'',N'',N'',N'',N''),
(N'Sao Tome and Principe',N' ST',N'',N'',N'',N'',N''),
(N'El Salvador',N' SV',N'',N'',N'',N'',N''),
(N'Syria',N' SY',N'',N'',N'',N'',N''),
(N'Swaziland',N' SZ',N'',N'',N'',N'',N''),
(N'Turks and Caicos Islands',N' TC',N'',N'',N'',N'',N''),
(N'Chad',N' TD',N'',N'',N'',N'',N''),
(N'French Southern Territories',N' TF',N'',N'',N'',N'',N''),
(N'Togo',N' TG',N'',N'',N'',N'',N''),
(N'Thailand',N' TH',N'',N'',N'',N'',N''),
(N'Tajikistan',N' TJ',N'',N'',N'',N'',N''),
(N'Tokelau',N' TK',N'',N'',N'',N'',N''),
(N'Turkmenistan',N' TM',N'',N'',N'',N'',N''),
(N'Tunisia',N' TN',N'',N'',N'',N'',N''),
(N'Tonga',N' TO',N'',N'',N'',N'',N''),
(N'Turkey',N' TR',N'There are huge public transport system in Turkey such as local buses, taxis, minibuses, tram and metro. Your choice of transport will depend on how quickly you want to get from A to B.All towns and cities have plentiful local buses which are cheap to use. You can purchase a smart ticket for a small deposit which, once loaded with credit, can be used not only on the buses but the metro, tram and ferries.Minibuses are useful alternatives to local buses and run on standard routes posted on the front screen of the vehicle.Taxis are plentiful and the best boarded at designated taxi stops. Payment is according to the on-board meter. All taxis in Turkey are required by law to have an on-board meter. However, set prices are more common for intercity journeys which are posted clearly at the taxi stop.Turkey''s metro system of underground and surface rapid transit trains is growing quickly. Major cities of Turkey now have the underground metros. You need to buy the smart ticket to travel by metro.Several cities also have overground trams, which are a quick and efficient way of getting around.',N'Turkish cuisine (Turkish: Turk mutfagi) is largely the heritage of Ottoman cuisine, which can be described as a fusion and refinement of Central Asian, Middle Eastern, Eastern European and Balkan cuisines.Turkish cuisine has in turn influenced those and other neighbouring cuisines, including those of Southeast Europe (Balkans), Central Europe, and Western Europe. The Ottomans fused various culinary traditions of their realm with influences from Levantine cuisines, along with traditional Turkic elements from Central Asia (such as yogurt and manti), creating a vast array of specialities.',N'Turkey is a country on the Mediterranean sea surrounded by Bulgaria and Greece to the west, and Armenia, Azerbaijan, and Georgia to the Northeast, Syria, Iraq and Iran to the southeast. Not only its breath-taking landscapes and rich history will make you eager to explore this country, but its welcoming people, culture, and delicious cuisine. Some areas of the country have to be avoided, while the main cities are welcoming for tourists.Emergency calls can be made from any phone free of charge: call 112 for ambulance and 155 for fire and police.',N'The culture of Turkey combines a heavily diverse and heterogeneous set of elements that have been derived from the various cultures of the Eastern Mediterranean (West Asian) and Central Asian region and to a lesser degree, Eastern European, and Caucasian traditions. Many of these traditions were initially brought together by the Ottoman Empire, a multi-ethnic and multi-religious state. During the early years of the republic, the government invested a large amount of resources into fine arts such as paintings, sculpture and architecture. This was done as both a process of modernization and of creating a cultural identity. Because of the different historical factors defining the Turkish identity the culture of Turkey combines clear efforts of modernization and Westernization undertaken in varying degrees since the 1800s with a simultaneous desire to maintain traditional religious and historical values.',N'Ataturk International Airport, Antalya Airport, Adnan Menderes Airport, Trabzon Airport, Dalaman Airport, Milas-Bodrum Airport, Kayseri Erkilet Airport'),
(N'Trinidad and Tobago',N' TT',N'',N'',N'',N'',N''),
(N'Tuvalu',N' TV',N'',N'',N'',N'',N''),
(N'Taiwan',N' TW',N'',N'',N'',N'',N''),
(N'Tanzania',N' TZ',N'',N'',N'',N'',N''),
(N'Ukraine',N' UA',N'',N'',N'',N'',N''),
(N'Uganda',N' UG',N'',N'',N'',N'',N''),
(N'Uruguay',N' UY',N'',N'',N'',N'',N''),
(N'Uzbekistan',N' UZ',N'',N'',N'',N'',N''),
(N'Saint Vincent and the Grenadines',N' VC',N'',N'',N'',N'',N''),
(N'Venezuela',N' VE',N'',N'',N'',N'',N''),
(N'Virgin Islands (British)',N' VG',N'',N'',N'',N'',N''),
(N'Virgin Islands (U.S.)',N' VI',N'',N'',N'',N'',N''),
(N'Vietnam',N' VN',N'',N'',N'',N'',N''),
(N'Vanuatu',N' VU',N'',N'',N'',N'',N''),
(N'Wallis and Futuna',N' WF',N'',N'',N'',N'',N''),
(N'Samoa',N' WS',N'',N'',N'',N'',N''),
(N'Yemen',N' YE',N'',N'',N'',N'',N''),
(N'Mayotte',N' YT',N'',N'',N'',N'',N''),
(N'South Africa',N' ZA',N'',N'',N'',N'',N''),
(N'Zambia',N' ZM',N'',N'',N'',N'',N''),
(N'Zaire (former)',N' ZR',N'',N'',N'',N'',N''),
(N'Zimbabwe',N' ZW',N'',N'',N'',N'',N''),
(N'United States of America',N' US',N'Public transportation in the United States refers to publicly financed mass transit services across the nation. This includes various forms of bus, rail, ferry, and sometimes, airline services. Most established public transit systems are located in central, urban areas where there is enough density and public demand to require public transportation.In more auto-centric suburban localities, public transit is normally, but not always, less frequent and less common. Most public transit services in the United States are either national, regional/commuter, or local, depending on the type of service. Furthermore, sometimes "public transportation" in the United States is an umbrella term used synonymous with "alternative transportation", meaning any form of mobility that excludes driving alone by automobile.This can sometimes include carpooling, vanpooling, on-demand mobility (i.e. Uber, Lyft, Bird, Lime), infrastructure that is fixated toward bicycles (i.e. bike lanes, sharrows, cycle tracks, and bike trails), and paratransit service.Most rail service in the United States is publicly funded at all tiers of government.Amtrak, the national rail system, provides service across the entire continental United States. The frequency of Amtrak service varies depending on the size of the city, and its location along major rail routes. For example, cities such as New York City and Washington, D.C. which are located along the busy Northeast Corridor may see up to 50 Amtrak trains per day come in an out of their stations. This same corridor is the location of the only operating high speed rail network in the Americas: the Acela Express.Other smaller cities, such as Dodge City, Kansas for instance, may only have two trains daily, or in rarer cases, cities in the upper Midwestern states, where there is sparse population, might only have Amtrak service two to three times per week. Regional rail services are primarily fixed on a major city or a state.For example, the Long Island Rail Road services the Long Island suburbs of New York City, while the UTA FrontRunner serves as a regional rail service for the Wasatch Front of Utah.These trains normally run throughout the entire day with service ranging from every 20 minutes during peak hours to every 30-45 minutes during off-peak hours. Other rail services that are regional in nature may only operate during rush hour. For example, the Virginia Railway Express (VRE), which services the Northern Virginia suburbs of Washington, D.C. only operates during the morning hours into Washington, D.C., and the evening hours out of Washington, D.C. VRE does not operate at night nor on the weekends, and only has one train during the middle of the day. Finally, several cities have light rail systems which operate generally in the core of the city and their surrounding suburbs. For instance, cities such as Kansas City, Norfolk, Boston, New Orleans, and Seattle have streetcar services that run every 10-15 minutes throughout their respective urban cores. ',N'American cuisine reflects the history of the US, blending the culinary contributions of various groups of people from around the world, including American Indians, African Americans, Asians etc. In the 20th century highly industrialized processed foods became a dominant feature of American diets.  American fast food today is heavily influenced by a variety of cuisines. From McDonald’s to Taco Bell to KFC, there’s nothing that screams more American than cheeseburgers, tacos, and fried chicken.',N'While it is generally a safe country for tourists, since it is so large, there are definitely parts of this country, and parts of particular cities that are best avoided, and that most locals never venture into.',N'The United States is one of the most culturally diverse countries in the world. Nearly every region of the world has influenced American culture, most notably the English who colonized the country beginning in the early 1600s. U.S. culture has also been shaped by the cultures of Native Americans, Latin Americans, Africans and Asians. The United States is sometimes described as a "melting pot" in which different cultures have contributed their own distinct "flavors" to American culture.',N'Hartsfield-Jackson Atlanta International Airport,Los Angeles International Airport,O''Hara International Airport,Denver International Airport,San Francisco International Airport'),
(N'Serbia',N'SRB',N'If you wish to travel to Serbia by plane, you should know there are three international airports in Serbia. The largest and most important is the Nikola Tesla airport in Belgrade. The second largest are the Constantine the Great airport in Niš and the Priština airport.Air Serbia is the national airline company, but there are also numerous other carriers flying to and from Serbia.The “Nikola Tesla” airport in Surčin is located 18 km from the centre of Belgrade. The airport is equipped to operate in all weather conditions.Well-developed rail network connects Serbia with all parts of Europe and Serbian Railways provide regular international and domestic traffic, so it is easy to travel to Serbia this way.If you prefer to travel by car, Serbia has well-developed road system and it is connected to all parts of Europe.Serbia is located on Pan-European Corridor 10 which is the shortest route between central/western and southernmost Europe.Belgrade is located at the intersection of the European E-70 and E-75 highways, highways E-75 and E-80 intersect in Niš, and highways E-80 and E-65 intersect in Priština.Foreigners in Serbia are required to have an international driver’s license, traffic permit and an insurance policy (green card).Regular bus lines connect Serbia all parts of Europe. The majority of departures are from Belgrade, and the Serbian capital is connected to all parts of the country.Belgrade is situated on the confluence of the Sava into the Danube. All major river transport corridors lead through Belgrade, and numerous international travel agencies offer Danube cruising which makes it easy to travel to Serbia by ship.',N'Serbian food is a typical Balkan mix of Central European and Near Eastern dishes. Serbs are very proud of their food, which is heavy on grilled meats and sausages, local cheeses and bread. Serbia is predominantly a meat-loving nation. In all major cities, there are many international restaurants, such as Italian and Chinese, Mexican, Thai, Lebanese, and Israeli. In Belgrade you can even find sushi or kosher food. ',N'Serbia is generally a very safe place to visit, with cities such as Belgrade being even safer than most big European cities. The locals are incredibly polite and helpful in case you require any assistance. (If you need any help finding/reaching a place, it''s best to ask a younger person for help, as they are more likely to speak English.) However, you should always be aware of pickpockets, mainly in crowded tourist places and on public transportation. In case of emergency. Below are some important telephones in case you may need assistance: Police - 192, Fire department - 193, Emergencies - 194, Assistance on the Road - 1987.',N'Being on the crossroads of Balkan routes, Serbian culture has for centuries preserved the identity and authenticity of Serbia and its people.Positioned on the crossroads of the main Balkan routes, Serbia has inherited a considerable cultural wealth. Among the remains of the tens of centuries old civilizations, there are traces of people who lived in this region 40,000 years ago, impressive Roman heritage, as well as medieval material and immaterial cultural wealth. ',N'Nikola Tesla Airport (BEG), Constantine the Great International Airport (INI) '),
(N'Montenegro',N'MNE',N'',N'',N'',N'',N''),
(N'Mjanmar',N'MMR',N'',N'',N'',N'',N'');
